# Introduction to Jupyter Notebook

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movie_prediction_dataset_final.csv')

In [3]:
df

,release_year,budget,runtime,is_sequel,director_name,director_popularity,lead_actor1,lead_actor1_popularity,primary_genre,genre2,studio_1,studio_2,brand_name,mpaa_rating,release_month,is_holiday_release,Distributor,First_Week_Income
0,2009,40000000,111,0,Mira Nair,1.3916,Hilary Swank,2.2810,Adventure,Drama,AE Electra Productions,Fox Searchlight Pictures,General,PG,10,0,Fox Searchlight Pictures,5305832.0
1,2009,237000000,162,1,James Cameron,4.3403,Sam Worthington,4.0107,Action,Adventure,Dune Entertainment,Lightstorm Entertainment,Avatar,PG-13,12,1,Twentieth Century Fox,137094051.0
2,2009,60000000,100,0,Henry Selick,1.6349,Dakota Fanning,7.9341,Animation,Family,LAIKA,Pandemonium,General,PG,2,0,Focus Features,20235921.0
3,2009,175000000,96,0,Pete Docter,1.3480,Ed Asner,1.4701,Animation,Comedy,Pixar,NaN,General,PG,5,0,Walt Disney Studios Motion Pictures,93072435.0
4,2009,70000000,153,0,Quentin Tarantino,3.8346,Brad Pitt,9.0310,Drama,Thriller,Universal Pictures,The Weinstein Company,General,R,8,0,The Weinstein Company,53703427.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3585,2025,23800000,93,0,Alex Parkinson,0.0618,Woody Harrelson,6.0845,Thriller,Drama,Dark Castle Entertainment,MetFilm Production,General,PG-13,2,0,Focus Features,10456885.0
3586,2025,9000000,107,0,Tony Tost,0.1493,Sydney Sweeney,21.2483,Crime,Thriller,Bron Studios,Creative Wealth Media Finance,General,R,8,0,NaN,NaN
3587,2025,8500000,118,0,Jon Avnet,0.3870,Neal McDonough,4.5676,Drama,NaN,Angel Studios,Unity Productions Foundation,General,PG,5,0,Angel,8607185.0
3588,2025,13000000,105,0,Johnny Martin,0.3193,Josh Duhamel,2.9623,Action,Thriller,Buffalo 8,Iervolino & Lady Bacardi Entertainment,General,R,6,0,NaN,NaN
3589,2025,15000000,105,0,Trey Edward Shults,0.6177,The Weeknd,1.0771,Music,Thriller,Manic Phase,Live Nation Productions,General,R,5,0,Lionsgate,4073964.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3590 entries, 0 to 3589
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   release_year            3590 non-null   int64
 1   budget                  3590 non-null   int64
 2   runtime                 3590 non-null   int64
 3   is_sequel               3590 non-null   int64
 4   director_name           3590 non-null   object
 5   director_popularity     3590 non-null   float64
 6   lead_actor1             3590 non-null   object
 7   lead_actor1_popularity  3590 non-null   float64
 8   primary_genre           3590 non-null   object
 9   genre2                  3055 non-null   object
 10  studio_1                3590 non-null   object
 11  studio_2                3089 non-null   object
 12  brand_name              3590 non-null   object
 13  mpaa_rating             3590 non-null   object
 14  release_month           3590 non-null   int64
 15  is_holiday_release      3590 non-null   int64
 16  Distributor             2276 non-null   object
 17  First_Week_Income       2246 non-null   float64
dtypes: float64(3), int64(6), object(9)
memory usage: 505.0+ KB

In [5]:
df.describe()

,release_year,budget,runtime,is_sequel,director_popularity,lead_actor1_popularity,release_month,is_holiday_release,First_Week_Income
count,3590.000000,3.590000e+03,3590.000000,3590.000000,3590.000000,3590.000000,3590.000000,3590.000000,2.246000e+03
mean,2015.775487,3.690934e+07,104.980223,0.228691,0.907292,4.010915,6.755153,0.159331,2.693013e+07
std,4.615776,5.320160e+07,19.005019,0.420048,1.302407,3.506618,3.383115,0.366036,4.161084e+07
min,2009.000000,5.000000e+00,4.000000,0.000000,0.000000,0.000000,1.000000,0.000000,6.000000e+02
25%,2012.000000,5.000000e+06,92.000000,0.000000,0.318700,1.553600,4.000000,0.000000,2.441046e+06
50%,2015.000000,1.600000e+07,102.000000,0.000000,0.574400,3.206000,7.000000,0.000000,1.351627e+07
75%,2019.000000,4.000000e+07,115.000000,0.000000,0.973200,5.358950,10.000000,0.000000,3.187987e+07
max,2025.000000,5.839000e+08,247.000000,1.000000,14.753800,27.711000,12.000000,1.000000,4.738946e+08

In [6]:
print(df['budget'])

0        40000000
1       237000000
2        60000000
3       175000000
4        70000000
          ...
3585     23800000
3586      9000000
3587      8500000
3588     13000000
3589     15000000
Name: budget, Length: 3590, dtype: int64

In [7]:
print(df[['runtime', 'release_year']])

      runtime  release_year
0         111          2009
1         162          2009
2         100          2009
3          96          2009
4         153          2009
...       ...           ...
3585       93          2025
3586      107          2025
3587      118          2025
3588      105          2025
3589      105          2025

[3590 rows x 2 columns]

In [16]:
high_budget_movies = df[(df['budget'] > 50000000) & (df['release_year'] == 2025)]

In [17]:
print(high_budget_movies['primary_genre'])

3468          Animation
3469              Drama
3470            Fantasy
3471             Action
3472             Action
3473           Thriller
3478            Fantasy
3480             Horror
3481              Drama
3482    Science Fiction
3484             Action
3485             Action
3486    Science Fiction
3488    Science Fiction
3489             Action
3490    Science Fiction
3491            Fantasy
3494             Family
3495    Science Fiction
3496             Action
3498             Family
3501            Romance
3502             Family
3503             Family
3509             Horror
3513             Action
3520          Animation
3521             Action
3528           Thriller
3530    Science Fiction
3534             Family
3544            Mystery
3549             Action
3560    Science Fiction
3563              Drama
3566             Comedy
Name: primary_genre, dtype: object

In [18]:
df['First_Week_Profit'] = df['First_Week_Income'] - df['budget']

In [20]:
df['First_Week_Profit']

0      -34694168.0
1      -99905949.0
2      -39764079.0
3      -81927565.0
4      -16296573.0
           ...
3585   -13343115.0
3586           NaN
3587      107185.0
3588           NaN
3589   -10926036.0
Name: First_Week_Profit, Length: 3590, dtype: float64

In [22]:
genre_income = df.groupby('primary_genre')['First_Week_Income'].median()

print(genre_income)

primary_genre
Action             25311178.5
Adventure          29287858.5
Animation          34081350.0
Comedy             12289153.5
Crime              11044810.0
Documentary          993565.0
Drama               3008611.0
Family             31855238.5
Fantasy            32635901.0
History             4915036.0
Horror             13173629.0
Music               9852768.0
Mystery            18889880.5
Romance             6891197.0
Science Fiction    30647660.5
TV Movie                  NaN
Thriller           10860233.0
War                 3069003.0
Western              827972.5
Name: First_Week_Income, dtype: float64

In [23]:
df.to_csv('processed_movies.csv')